import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="lg:flex lg:flex-row">
          <div className="lg:fixed  left-0 top-0  bg-gray-900 w-full h-screen text-white flex justify-between flex-col">
            <div className=" sticky z-50 ml-10 mt-20 ">
              <Header />
            </div>
            <div className="flex flex-col gap-y-4 ml-10">
              <h1 className="text-4xl font-bold">Capable alone,</h1>
              <h1 className="text-4xl font-bold">Exceptional together</h1>

              <p className="leading-none">
                1인분도 못하는 개발자에 지치셨나요?{" "}
              </p>
              <p className="leading-none">
                혼자 서비스와 상용화가 가능한 개발자 김영우 입니다 :)
              </p>
            </div>
            <div className="ml-10 mb-20">
              <Footer />
            </div>
          </div>

          <main className=" lg:w-1/2 lg:ml-[50%] lg:mt-0  w-full ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
